Adding tests and some missing a11y attributes
liqd/zt-app pull request #460
Opened 2023-03-27 14:27 UTC by philli-m

2023-03-28 15:42 UTC, goapunk commented on src/components/ImagePickerFormField.js
> +          testID={'camera-image'}
the testID is unused and can be removed

2023-03-28 15:42 UTC, goapunk commented on src/components/ImagePickerFormField.js
> +          testID={'library-image'}
the testID is unused and can be removed

2023-03-28 15:43 UTC, goapunk commented on src/components/ImagePickerFormField.js
> +        testID={'remove-image'}
the testID is probably unnecessary and can be removed

2023-03-28 15:45 UTC, goapunk commented on src/components/__tests__/ImagePickerFormField.test.js
> +    expect(getByTestId('remove-image')).toBeTruthy()
you should be able to use `byLabelText('Remove image')` here, according to the docs it will find the `accessibilityLabel` value

2023-03-28 15:48 UTC, goapunk requested changes
see comments

2023-03-28 15:53 UTC, goapunk commented on src/components/__tests__/VirtualScrollView.test.js
> +    expect(getByTestId('child')).toBeTruthy()
could this just use `getByText` instead of `getByTestId` ?

2023-04-04 07:15 UTC, khamui commented
working fine! and tests are nice!

2023-04-04 07:15 UTC, merged